name: my_meltano_project
version: "1.0"
require-dbt-version: [">=1.0.0", "<2.0.0"]
profile: meltano
config-version: 2
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: logs
packages-install-path: dbt_packages
clean-targets:
  - ../.meltano/transformers/dbt/target
  - dbt_packages
  - logs
models:
  my_meltano_project: null
