#
# Staging / Prod kubernetes config
#
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: full
xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/keystore.p12
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: full
xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/keystore.p12
