# This file is managed by the 'files-dbt' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files files-dbt set _update transform/profile/profiles.yml false

config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    snowflake:
      type: snowflake
      threads: 2
      account: "{{ env_var('TARGET_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('TARGET_SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('TARGET_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('TARGET_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('TARGET_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('TARGET_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('TARGET_SNOWFLAKE_SCHEMA') }}"
    postgres:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "{{ env_var('TARGET_POSTGRES_SCHEMA') }}"
    postgres_transferwise:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "{{ env_var('TARGET_POSTGRES_DEFAULT_TARGET_SCHEMA') }}"
    bigquery:
      type: bigquery
      threads: 2
      method: service-account
      project: "{{ env_var('TARGET_BIGQUERY_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_TARGET_SCHEMA') }}"
      keyfile: "{{ env_var('TARGET_BIGQUERY_CREDENTIALS_PATH') }}"
      location: "{{ env_var('TARGET_BIGQUERY_LOCATION') }}"
